name: Lint & Format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy isort black types-requests
    - name: flake8
      run: |
        flake8 --ignore E203,E501,W503 $(git ls-files '*.py')
    - name: isort
      run: |
        isort -l 120 --profile black $(git ls-files '*.py')
    - name: black
      run: |
        black --line-length 120 $(git ls-files '*.py')
    - name: mypy
      run: |
        mypy --ignore-missing-imports $(git ls-files '*.py')
